### ISSUE TITLE
`sre_constants.error: bad character range` on ca1 site

### ISSUE THREAD

**Issue by MichaelSnowden** [freelawproject/juriscraper#188]
Ran into this error after following the installation steps on Python 2.7.13 on macOS 10.12.6.

```
>>> site = ca1.Site()
>>> site.parse()
2017-09-30 10:06:50,466 - INFO: Now downloading case page at: http://media.ca1.uscourts.gov/cgi-bin/opinions.pl/?TODATE=09%2F30%2F2017&puid=&FROMDATE=09%2F23%2F2017
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/michael.snowden/.virtualenvs/py2/lib/python2.7/site-packages/juriscraper/AbstractSite.py", line 98, in parse
    self.html = self._download()
  File "/Users/michael.snowden/.virtualenvs/py2/lib/python2.7/site-packages/juriscraper/AbstractSite.py", line 287, in _download
    return self._return_response_text_object()
  File "/Users/michael.snowden/.virtualenvs/py2/lib/python2.7/site-packages/juriscraper/AbstractSite.py", line 343, in _return_response_text_object
    text = self._clean_text(payload)
  File "/Users/michael.snowden/.virtualenvs/py2/lib/python2.7/site-packages/juriscraper/AbstractSite.py", line 126, in _clean_text
    return clean_html(text)
  File "/Users/michael.snowden/.virtualenvs/py2/lib/python2.7/site-packages/juriscraper/lib/html_utils.py", line 114, in clean_html
    u'\U00010000-\U0010FFFF]+', u'', text)
  File "/Users/michael.snowden/.virtualenvs/py2/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/Users/michael.snowden/.virtualenvs/py2/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
sre_constants.error: bad character range
>>> 
```

**Comment by voutilad** [comment]
Seems to be a Python2 issue at least on macOS. Simple reproduction:
```
re.compile(u'[\U00010000-\U0001FFFF]')
```

**Comment by voutilad** [comment]
This is coming deep in the bowels of Python's regular expression lib, specifically https://github.com/python/cpython/blob/2.7/Lib/sre_parse.py#L489

```
(Pdb) s
> /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sre_parse.py(489)_parse()
-> raise error, "bad character range"
(Pdb) l
484                             if code1[0] != LITERAL or code2[0] != LITERAL:
485                                 raise error, "bad character range"
486                             lo = code1[1]
487                             hi = code2[1]
488                             if hi < lo:
489  ->                             raise error, "bad character range"
490                             setappend((RANGE, (lo, hi)))
491                         else:
492                             raise error, "unexpected end of regular expression"
493                     else:
494                         if code1[0] is IN:
```

**Comment by voutilad** [comment]
@mlissner opened a PR just showing a possible change, but it's not clear if it's functionally correct. Current `master` branch doesn't have passing tests on my machine with this change and haven't' dug into if I'm unearthing real issues or creating new.

**Comment by mlissner** [comment]
OK, good news. I finally spent some time last night getting to the bottom of this damned thing, since it bit yet another person. Bad news: It's because Python (for reasons I don't care to look into) made a decision at some point (I guess it made sense at the time?) to have two kinds of unicode handling. This resulted in "narrow" and "wide" builds of Python in the 2.7 series. In Py3, this is distinction is removed.

Guess what? The wide builds, which are default on real computers (aka Linux), work fine, and the narrow builds, which seem to come on Macs, throw the error above. (I'm kidding about Linux, btw — or am I?)

There are two possible solutions here. One complicates the code but works properly. The other keeps the code simple, but means that you may have corner-case kinds of errors parsing documents on narrow builds (aka Macs). I've chosen to keep the code simple, log an error at import time on narrow builds, and to move on. 

If you're curious if you have a narrow build:

    import sys
    if sys.maxunicode == 65535:
        print "You have a narrow build. Bummer."

The corner case error that you may run into is that if you are parsing documents that contain characters in the following range...

    u'\U00010000-\U0010FFFF'

...they won't get removed from the document before parsing. That means that the XML parser will fail since these are invalid characters in XML. The solution at that point will be to either:

 - remove those bytes in your own pre-parser;
 - compile and install a wide build of Python; or
 - not parse the document in the first place.

My thinking on this was forged by [this answer on Stackoverflow](https://stackoverflow.com/questions/31603075/how-can-i-represent-this-regex-to-not-get-a-bad-character-range-error).
