### ISSUE TITLE
PacerLoginException: Did not get PacerSession and NextGenCSO cookies

### ISSUE THREAD

**Issue by j2kao** [freelawproject/juriscraper#255]
Firing up juriscraper again today, and I'm getting the below error re cookies that I didn't when I used it last year. Any advice on how to fix this? (hopefully it's not a site change?)

Jeff

```
2019-03-25 16:43:43,451 - INFO: Attempting PACER site login
2019-03-25 16:43:44,171 - INFO: Did not get cookies from first log in POST. Assuming this is a filing user and doing two more POSTs.
---------------------------------------------------------------------------
PacerLoginException                       Traceback (most recent call last)
<ipython-input-14-d7983aecd24e> in <module>()
----> 1 sess.login()

/home/ubuntu/juriscraper/juriscraper/pacer/http.pyc in login(self, url)
    268                 not self.cookies.get('NextGenCSO'):
    269             raise PacerLoginException(
--> 270                 'Did not get PacerSession and NextGenCSO '
    271                 'cookies when attempting PACER login.'
    272             )

PacerLoginException: Did not get PacerSession and NextGenCSO cookies when attempting PACER login.
```

**Comment by mlissner** [comment]
We just started getting this error too late last week. Any chance you could take a look into the login flow? Seems like something must have changed on the PACER site somewhere. :(

**Comment by johnhawkinson** [comment]
https://github.com/freelawproject/juriscraper/blob/5e6550fcb3681fe70e9304be30f8dc5f55b7b39f/juriscraper/pacer/http.py#L266-L271

Why is this code looking for the `NextGenCSO` cookie, or any specific cookie? Why isn't it a feature test?

I don't know how this used to work, but in quick tests, a Legacy court (`ecf.mad`) gives a PacerSession and no NextGenCSO cookie, but a NextGen court (`ecf.nyed`) gives both.

_(Rhetorical: I see f956334969c2658a89a13268049c85b497e9dc0b and I suspect that's part of the answer, but also that it seems like the wrong answer. Obviously 20/20 hindsght.)_

p.s.: This code would, to my eye, have been a lot clearer if it was `not all(self.cookies.get('PacerSession'), self.cookies.get('NextGenCSO'))`...

**Comment by mlissner** [comment]
How would you feature test it?

**Comment by j2kao** [comment]
> We just started getting this error too late last week. Any chance you could take a look into the login flow? Seems like something must have changed on the PACER site somewhere. :(

I have to confess I'm not very good at debugging http stuff (hence why I'm using this excellent module). If I end up figuring out what has gone wrong I will definitely let you know though. :-(

**Comment by arderyp** [comment]
> This code would, to my eye, have been a lot clearer if it was `not all(self.cookies.get('PacerSession'), self.cookies.get('NextGenCSO'))`...

oof, please no.  Not to mention that `all()` in this context requires both cookies to be present, whereas the current logic requires only 1 (or the other) to be present...

**Comment by mlissner** [comment]
I'll take this on. It's urgent.

**Comment by j2kao** [comment]
Thanks -- II can get around my current problem just downloading manually but I'm sure this will get a lot of people unstuck. Appreciate it.

**Comment by mlissner** [comment]
Looks like the login flow did change and now you have to select one more input box before you submit your password. Working on it now.

**Comment by johnhawkinson** [comment]
> Looks like the login flow did change and now you have to select one more input box before you submit your password. Working on it now.

I don't think that's correct. Nextgen login has always required checking of the FRCP 5.2(c) checkbox for accounts with filing privileges, because CMECF requires it for all ECF accounts (including nonfiling ones, sigh…), and PACER doesn't know whether a NextGen account is an ECF account at the time of login (or maybe…ever?). So the checkbox has been required for…months or years on Nextgen logins. It's definitely not a change in the past week.

I can, e.g. log in to `ecf.nyed` (through `https://pacer.login.uscourts.gov/csologin/login.jsf?pscCourtId=NYEDC&appurl=https://ecf.nyed.uscourts.gov/cgi-bin/showpage.pl?16`)  with my nextgen account that's not linked to anything, and I don't get the checkbox popup. But logging in with my regular account that is linked and I do. This is…nothing new.

**Comment by mlissner** [comment]
That's not the change. There's a new box that requires you input your destination:

![Screenshot from 2019-03-25 12-55-26](https://user-images.githubusercontent.com/236970/54949894-4dc59e80-4efd-11e9-9b1e-6500e1dab9be.png)

Alas, just putting a valid value in there isn't enough. You also have to now pass the ViewState parameters for each request you make, which means you have to parse them out of the form each time. 

For extra fun, PACER sends either HTML forms or XML forms that you have to parse, so I'm experimenting with writing a quick parser for each of those. Pretty janky, but if we need the ViewState parameters and we don't want to use selenium, I think this is the best way. (Though Selenium is looking more and more necessary.)

**Comment by johnhawkinson** [comment]
Ah. Of course, this doesn't appear at the URL I gave.
I guess it only happens if you start directly at `https://pacer.login.uscourts.gov/csologin/login.jsf` rather than getting there from an ECF instance.

**Comment by johnhawkinson** [comment]
> How would you feature test it?
Well, certainly not by looking for some kind of internal state that is going to change.

The best feature test is actually to run a CMECF function that requires being logged in, like running a query. But that seems far too expensive (time, round trips).

So then instead would be parsing the result to confirm it works.

```xml
<?xml version='1.0' encoding='UTF-8'?>
<partial-response id="j_id1">
  <redirect url="https://ecf.mad.uscourts.gov"></redirect>
</partial-response>
```

Seems to be the normal situation. I assume we wouldn't ever follow that redirect directly, but searching for the presence of a redirect at all might be ok? Not the best feature test, though, what if they change it to just return a HTTP 302 instead of a HTTP 200?

Another approach would be to look for the failure patterns, e.g. take the failure today::

```html
<div id="loginForm:j_idt248"
  aria-live="polite" class="psc-login-input-error ui-message
  ui-message-error ui-widget ui-corner-all">
    <span class="ui-message-error-detail">Court: Validation Error: Value is required.
    </span>
</div>
```

so searching for that span class might be wise, and otherwise assuming success.
Esp. since code further along the way should be robust enough to throw failures?

<hr>
> oof, please no. Not to mention that all() in this context requires both cookies to be present, whereas the current logic requires only 1 (or the other) to be present...

Errr…perhaps I am confused, but I thought the current logic was requiring both cookies to be present, and now the NextGen cookie is not always present, so we have a problem. If the intent is to require both present, `all()` seems clearer.

**Comment by arderyp** [comment]
https://github.com/freelawproject/juriscraper/blob/5e6550fcb3681fe70e9304be30f8dc5f55b7b39f/juriscraper/pacer/http.py#L266-L271

```
if not A and not B:
    raise Exception
```

So both A and B must be false to reach the exception--that is, both cookies must be missing.  Otherwise, if cookie A is present, or cookie B is present, no exception.  

I didn't write that code, so I can't say whether that's the intended logic, but my guess is that it _is_ the intended logic, as the syntax is quite simple and straight forward.  I won't say it's "pythonic" because its just a simple conditional that would be written this way in almost all programming languages (that I'm familiar with, anyways).  There are indeed some weird "pythonic" approaches to syntax, but I've never seen that usage of `all()` among them.  In fact, python gives us the handy `and` and `or` operators in English syntax to make the code above more clear to the reader.

**Comment by johnhawkinson** [comment]
Well, I guess my point is we'd be better off with `not any(…)`.
But perhaps I just need more sleep.

**Comment by arderyp** [comment]
I see what you are saying, but I believe all of the approaches below are synonymous. Since the first is the shortest and most "standard" across popular languages, I see it as the most clear (all subjective I suppose):

```
if not (A and B):
    raise Exception
```

```
if not all(A and B):
    raise Exception
```

```
if not any(A and B):
    raise Exception
```

**Comment by johnhawkinson** [comment]
Well, of course they're synonymous. This is commentary on style, not function.
But I would observe that there's a significant parseability difference between the two `either or` choices where, as here, the expression spans multiple lines (albeit only two):

```py
        if not self.cookies.get('PacerSession') and \
                not self.cookies.get('NextGenCSO'):
```

So of course you have to read the second line. Whereas if it was

```
        if not any([self.cookies.get('PacerSession'),
                self.cookies.get('NextGenCSO')]):
```

You wouldn't have to think about the second line. Plus no nasty backslashes…

**Comment by arderyp** [comment]
Yeah, I also wouldn't break over two lines.  You're right about the back slash
