### ISSUE TITLE
can be python 3 used?

### ISSUE THREAD

**Issue by Sandy4321** [freelawproject/juriscraper#257]
great project thanks
but how to use with python 3?

**Comment by mlissner** [comment]
We've had a few efforts to get Jursicraper up to py3, but they hadn't succeeded yet. If you wanted to try to make the final push to get it over the finish line, we'd definitely appreciate that. 

The hard part is:

1. Getting the py3 compatible, and then
2. *Keeping* it py3 compatible. 

IIRC, I dropped compatibility not too long ago when I ran into something that worked in py2 but not py3. I think I made a bunch of notes about it in the git messages, if you grep them. 

We'd definitely appreciate the help if you can provide it, but we're (rather unfortunately) not in a huge rush to accomplish Py3 compatibility just yet. We'll be laggards because we have so many dependencies in CourtListener that we're still waiting on. Until our underlying libraries are compatible it's almost impossible for us to upgrade (without manually fixing all of those as well!).

**Comment by Sandy4321** [comment]
I see, by the way what can be used for Canada?

**Comment by audiodude** [comment]
I believe this is the commit @mlissner is referring to:

https://github.com/freelawproject/juriscraper/commit/c7b6fef5b9e7177481542be7651ac35aa5571aa3

**Comment by arderyp** [comment]
this should be an immediate priority, no?

@mlissner

**Comment by mlissner** [comment]
Yeah, getting py3 working here would be great, and that's part of why I just set up Sentry (see the #development channel on Slack from today). It shouldn't be hard to get it set up. It'll need to support both py2 and py3 so that we can maintain both until the rest of CL is ready to make the jump.

**Comment by cgdeboer-toptal** [comment]
@Sandy4321 `juriscraper` is now a Python 3 project (2.0.0 or later)

**Comment by mlissner** [comment]
Thanks @cgdeboer-toptal. Closing.
