### ISSUE TITLE
Create new parser for PACER mobile site

### ISSUE THREAD

**Issue by mlissner** [freelawproject/juriscraper#315]
The PACER mobile site is a useful place to learn about dockets because it shows the number of entries in each docket — for free. 

We need a new parser to query it and parse the results. Because these results can sometimes cost money, the parser should include the cost of each query, if applicable.

**Comment by ikeboy** [comment]
If we only use a docket number to search, are we guaranteed to not be charged?

What do you mean by "include the cost of each query"? Return it?

**Comment by johnhawkinson** [comment]
> If we only use a docket number to search, are we guaranteed to not be charged?

That's my understanding with high confidence.

> What do you mean by "include the cost of each query"? Return it?

Yes. The parser should parse the receipt/cost info at the bottom of the query and return it as part of the structured information. This is not something that happens for the existing PACER parsers, although there isn't a good reason why it shouldn't.

**Comment by mlissner** [comment]
If docket numbers will never charge us, then we don't need to bother returning the cost. We haven't needed it yet elsewhere and I think we can not bother here either, until we need it. Sorry John, I know that's not what you'd advise, but for now it falls into [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it)

**Comment by johnhawkinson** [comment]
It's your dollar, but it's so easy to parse, and…:

1. What if we're wrong? I said "high confidence," but… (turns out I'm wrong! See below.)
1. What if there's a bug (ours or PACER's)?
1. What if they change it? There's reason to be concerned that this is currently a free endpoint but there's not a lot of good reason for it to be (mobile users probably don't care), and there's a reasonable fear that mass beating on it may cause that to change.

_Belt and suspenders, right?_

Also, after some further thought, I thought of at least one case where I indeed **am wrong**. Thanks for pushing me:

* Docket number changes. They don't happen often, but they _do_ happen. In my experience, most often a change in office code when a case moves, but there may be other situations too.
* Docket number deletions. These in fact happen regularly. Usually as a result of attorney errors, but those are not exactly rare. This is because as a CMECF user is opening a case, a docket number is assigned fairly early in the process, before all information has been entered, like parties and case metadata. (In part it is engineered this way so that you can punch in the case number into your case-initiating-document and generate the PDF and then upload it to the system, so the docket number is neatly printed in the caption block.) So if an attorney gets interrupted, or typos something that they cannot get back to, or  probably various other things, there are these abandoned, nascent and stillborn dockets. Usually the QA people at the Court go through and reap them, maybe once a week or so, and then they get returned to the pool of available docket numbers and get reused. It's relatively rare that someone would enter an alert for such a thing in CourtListener, presumably, but it could happen. (And I can think of some plausible cases where it might.)

**Comment by mlissner** [comment]
OK, sold. Let's build these in, and we'll have to think about how to actually use these. It'd be great to have a switch somewhere to completely disable mobile crawling if charges start appearing (or just a per-alert setting would be good too). At a minimum, we need email alerts, I suppose.

**Comment by ikeboy** [comment]
I found a different endpoint that uses the caseid directly _and_ doesn't charge money if the id isn't found. 

`/cgi-bin/mobile_query.pl?search=caseInfo&caseid=CASEID`

Going to refactor to use this instead, obviously preferable.
