### ISSUE TITLE
Georgia Supreme Court appears broken

### ISSUE THREAD

**Issue by flooie** [freelawproject/juriscraper#371]
Georgia Supreme Court is scraping HTML content since 2016 
[See broken opinion](https://www.courtlistener.com/opinion/4863856/pender-v-state/?q=Oral%20Argument%20Calendar&type=o&order_by=dateFiled%20desc&stat_Precedential=on&court=ga)

**Comment by mlissner** [comment]
Not great.

**Comment by arderyp** [comment]
oy.  I must have introduced this.  Fixing now.. I guess we will need a backscraper to resolve this issue, or what do you suggest @mlissner ?

**Comment by mlissner** [comment]
Yep, that's probably what'll take or else some sort of import script outside of Juriscraper. Bill has been preferring those lately because it lets him write up some script that generates a JSON file that I then import, but I'm happy either way.

**Comment by arderyp** [comment]
okay, I will re-open for now.  I am not sure how the import script process works--I've been away a little too long.  Any guidance @flooie? Or would you rather do it yourself?

**Comment by mlissner** [comment]
He usually does something out of my sight that generates a JSON file, and then tells me how to import it. That's working well for other object types, but I guess it's only because he already has import scripts for those JSON files too that *are* in CL. So maybe it's better to stick with the usual backscraper approach.

**Comment by mlissner** [comment]
I guess we're also going to want to delete and clean up all the messed up ones too, which could be a bit of a pain, but probably not too horrible.

**Comment by arderyp** [comment]
> I guess we're also going to want to delete and clean up all the messed up ones too, which could be a bit of a pain, but probably not too horrible.

Sorry :disappointed:

**Comment by mlissner** [comment]
Just a part of the deal! It happens.

**Comment by flooie** [comment]
Hey guys... sorry to miss the fun.  I'm up for whatever.  I think it makes the most sense to just add a back scraper.  But I'm open to either.

**Comment by flooie** [comment]
You know I take it back....  the case names are correct and so are the dates, and titles, precedential status and court. I think we just fix the current scraper and just import the documents.

And since I lived the largest percentage of my life in Georgia still I can pull down the cases and pdfs and send @mike an import script to fix the current mistakes tomorrow.  If @arderyp you just want to fix the broken scraper moving forward that would work for me?

**Comment by arderyp** [comment]
I just added a backscraper and a new test example

**Comment by arderyp** [comment]
@flooie , the scraper and back scraper should be good to go.  @mlissner, does @flooie need to go through the work of scripting if the backscraper works?  Wouldn't want to make him do redundant work, especially since this was my screw up :)

As for fixing the scraper moving forward, once upon a time I would fix any/all scrapers that I noticed going down.  I've been on a bit of sabbatical recently though, but hope to involve myself a little more.

**Comment by mlissner** [comment]
I'm really glad to have you back, @arderyp. I have an idea that might make everything work better: What if I stop trying to help and @flooie became your insider. I suspect he would do a much better job at this than I would, since he knows how to corral my attention via Zoom meetings and such. I think I might be at the point where I need that kind of help (I know I've done a terrible job helping you @arderyp, and this project is a in a not great place.)

**Comment by arderyp** [comment]
happy to help however I can, time affording, and happy to engage with whoever.

**Comment by flooie** [comment]
Resolved.
