### ISSUE TITLE
Fix opinion scraper for the Illinois Supreme Court

### ISSUE THREAD

**Issue by satsuki-chan** [freelawproject/juriscraper#405]
Includes opinions scrapers for the **Illinois Supreme Court** and the **Illinois Appellate Court**

```
juriscraper.opinions.united_states.state.ill
juriscraper.opinions.united_states.state.illappct
```

**Comment by flooie** [comment]
@satsuki-chan is working to fix the Illinois scraper, but a few questions remain as to what to do exactly. 

Illinois to its credit likes to publish opinions and rule 23 decisions that do not establish new law.  

But in Nov 2020, and beginning in 1/1/2021 the Illinois Supremes modified rule 23 to be used as precedential case law for specific circumstances.  At least according to [this blog post](https://chicagocouncil.org/illinois-supreme-court-amendment-to-rule-23/) from the Chicago Council.

This seems to me that we should mark all decisions posted as precedential, both opinion and Rule 23.  @mlissner That is question 1.

The second question is this ... they do withdraw opinions and Rule 23 decisions because when it is first posted - it can be reheard.  Both rule 23 and opinions have been withdrawn at times.

The website states its basically 21 days from the decision to get a rehearing. It's unclear how often it happens or how quick they are at fixing it online.  This makes me think we should just wait 1 month or maybe 6 weeks before scraping Illinois.  But I'm not sure exactly how that mechanism would work with CL.  Would this mean we would change the scraper from CL to a back scraper?

**Comment by mlissner** [comment]
After some lengthy discussion today, we've got the following action items moving forward:

1. Bill will ask the court to add our opinions email address to their distribution list. That'll collect some data.

2. Grecia will adapt our scraper to mark all future Illinois Supreme Court docs as precedential. 

3. Bill, can you go in the live DB (or we can do this together), and update it to make all Illinois SC opinions precedential? 

4. Because of the change to Rule 23, every opinion from the appellate courts of Illinois are basically precedential after Jan 1, 2021. Gracia will update our scrapers accordingly. 

    For appellate court cases before Jan 1, 2021, any case with the text "Rule 23" in its body is not precedential. We need to update these cases. Bill, can you go into the DB and adjust this as well, please?

4. Grecia will add a tweak to CourtListener's opinion HTML page to note that the appellate opinions can be withdrawn, and that before assuming something is good law, a check should be made to the Illinois website. This is lame, but it's a good workaround for us, so we don't have to retract docs from our system. @flooie, will you propose some language for this? @satsuki-chan, the file to update is `cl/opinion_page/template/view_opinion.html`.

**Comment by satsuki-chan** [comment]
Pull request for added comment in CourtListener:
https://github.com/freelawproject/courtlistener/pull/1802

**Comment by mlissner** [comment]
There are still a few outstanding things here, but I think your work is done here, @satsuki-chan. @flooie can you take a look at your piece, please?

**Comment by flooie** [comment]
Lets update #4 

4. For appellate court cases before Jan 1, 2021, any case with the text "Rule 23" in its body is not precedential. We need to update these cases. Bill, can you go into the DB and adjust this as well, please?

After listening to an actual attorney in Chicago and re-reading the rule - Rule 23 should remain non-precedential.  @satsuki-chan 

The cases are allowed to be persuasive but certainly not binding.

This should be a simple enough tweak - or tweak back.

**Comment by satsuki-chan** [comment]
In the latest review, the status validation is based on the _**ending**_ of the opinion or ruling _**citation**_.
If the citation ends with an '-U' (or '-U[X: any char]'), the document's status is "Unpublished". if it has other ending ('-B', or '-C') or none, the document has a "Published" status.

**Comment by mlissner** [comment]
What's left here?

**Comment by flooie** [comment]
We need to bump and deploy, 1.

**Comment by mlissner** [comment]
The bump and deploy is done. 

That leaves calling the court and cleaning up old decisions. Once you get the disclosures in, can you take a stab at these, @flooie?

**Comment by mlissner** [comment]
Sorry to say this isn't done:

 - [ ] Get opinions emailed to our inbox from the court

**Comment by flooie** [comment]
Follow up email sent to the court.

**Comment by mlissner** [comment]
How did the last piece of this go?

**Comment by flooie** [comment]
The court apologized for the delay and emailed the document to opinions@free.law

**Comment by mlissner** [comment]
What about:
 - [ ]  A survey needs to be done to see how many (if any) opinions need to be changed via status.

**Comment by flooie** [comment]
womp womp

**Comment by flooie** [comment]
@mlissner I don't think we need to change any opinions.

**Comment by flooie** [comment]
@mlissner the previous code - set NREL to unpublished ( I believe), but to complicate things - the previous juriscraper code dropped the -U that indicated unpublished opinions.  But doing a spot check, I haven't found any opinions that would need to be fixed.  And since we don't have the -U flag on the citations from earlier - I don't have a good way to validate all of the opinions.

**Comment by flooie** [comment]
@mlissner as such I believe this is closed.
