### ISSUE TITLE
Propose adding new optional attribute `child_court`

### ISSUE THREAD

**Issue by flooie** [freelawproject/juriscraper#847]
I want to add a new optional attribute for case objects to include the child court string name. 

This will let us add the new lower court scrapers but also find the best data in CL

**Comment by mlissner** [comment]
Can you share an example of how this would work with some pseudo-code, maybe?

**Comment by grossir** [comment]
On the juriscraper side, this would mean returning a new field, child_court

On the courtlistener side, these are the changes needed:
https://github.com/freelawproject/courtlistener/compare/main...grossir:process_child_court?expand=1

and the explanation:

NY Misc Reporter has opinions for a few hundred small courts, which we have grouped into 10 families, each with its own scraper. To avoid both losing data granularity and avoid creating a scraper for each court, juriscraper will return a child_court field for each opinion, which will be transformed into the proper court object . This changes the usual way, where the court object is obtained from the scraper module name.

Duplicate checking would not be affected, since it does not uses the court object. DupChecker:
- first uses the court url to check if the site is the same
- then checks the downloaded content to check if it changed

**Comment by flooie** [comment]
Thanks @grossir

**Comment by mlissner** [comment]
Got it. Yeah, this sounds logical to me. We should link this with the other issue where we're discussing it though. I didn't immediately realize it was the same thing.

**Comment by flooie** [comment]
Sorry

**Comment by flooie** [comment]
This is complete thanks @grossir
